### ISSUE TITLE
Settings::all() method does not work as expected

### ISSUE THREAD

**Issue by assoft** [iamohd/laravel-settings#2]
Hi @iamohd 

|id|group|key|payload|
|---|---|---|---|
|1|title|null|{"$cast": null, "value": "Site Title"}|
|2|description|null|{"$cast": null, "value": "Site Description"}|
|3|email|null|{"$cast": null, "value": "email@site.com"}|
|4|per_page|admin|{"$cast": null, "value": 10}|

```php
Settings::all();
```

If this query works, you will see that records belonging to any group **are excluded**.

I don't know why this behavior is exhibited. But there is a way to fix it with a little tap.

`vendor/smartisan/laravel-settings/src/Repositories/DatabaseRepository.php`

```php

protected function getEntries($keys, $default)
{
    ...
    return DB::connection($this->connection)
        ->table($this->table)
       ...
       // ->where('group', $group) // replace with below code
       ->when($group, function (Builder $builder) use ($group) {
           $builder->where('group', $group);
       })
      ...
}
```

It can now continue to work as expected.

**Also, `Settings::paginate($perPage)` wouldn't be bad at all.**

Thank you.

**Comment by iamohd-zz** [comment]
Hi @assoft 

This is actually the intended behavior. Consider settings with a "null" group and no model set as global settings.

Maybe we can introduce a new filter method to retrieve everything at once, something like:

```php
Settings::withAllGroups()->all();
```

What do you think?

**Comment by assoft** [comment]
Yes I understand but;

`Settings:all()` means this 'all' method will call all records without excepted; I think there is some confusion here.

```php
Settings:all() // for all models
Settings::group('foo')->get() // for group `foo`
Settings::group('bar')->get() // for group `bar`
```

This is obviously more in line with the **Laravel Naming Conventions**.

Of course, the decision is yours here.

**Comment by iamohd-zz** [comment]
Yea all method might be a bit confusing here. But what do you suggest for retrieving settings that has no group?

**Comment by Restingo** [comment]
> Hi @assoft
> 
> This is actually the intended behavior. Consider settings with a "null" group and no model set as global settings.
> 
> Maybe we can introduce a new filter method to retrieve everything at once, something like:
> 
> ```
> Settings::withAllGroups()->all();
> ```
> 
> What do you think?

@iamohd did you already implement this? Would be very helpful! Thank you sir.

**Comment by iamohd-zz** [comment]
Hi @Restingo 

I didn't implement it.

The problem with it is, it's not possible to have the same settings key in two different groups.

Suppose the following:

```php
settings()->group('g1')->set('k1', 'v1');
settings()->group('g2')->set('k1', 'v2');
```

And now you try to retrieve everything from the table

```php
Settings::withAllGroups()->all();
```

You will not be able to have both values since they have the same key.

So I suggest implementing your own logic, or simply retrieve everything directly from the table using DB::table

**Comment by Restingo** [comment]
Can't you just return an array of groups with the settings?

**Comment by iamohd-zz** [comment]
If you are going to retrieve entries as group => value

What about settings entries that have no group?

one solution might be to include all entries that have no group under 'no_group' key, but that feels like a hacky solution.
