### ISSUE TITLE
 Associative Arrays

### ISSUE THREAD

**Issue by ke-helle** [iamohd/laravel-settings#3]
Hi, a smal question. 
How do you check the setting if saved as an associative array. In the instance under, check the value of the K5 value.
`Settings::group('application')->get('k2.k4.k5', false); `
doesnt work.

```
Settings::group('application')->set([
    'k1' => Carbon::now(),
    'k2' => [
        'k3' => $user,
        'k4' => [
            'k5' => true
        ],  
    ]
]);
```

**Comment by Restingo** [comment]
You need to load setting `k2` and then you can work with the array:

`Settings::group('application')->get('k2');`

```
=> [
     "k3" => null,
     "k4" => [
       "k5" => true,
     ],
   ]
```

Or you write it directly:

`Settings::group('application')->get('k2')['k4']['k5'];`

`=> true`
